# sozu proxy simple demo config file

command_socket = "./command_folder/sock"
saved_state    = "./state.json"
log_level      = "info"
log_target     = "stdout"
command_buffer_size = 16384
worker_count = 3
handle_process_affinity = false

# you need this, but currently it`s not used
[metrics]
address = "192.168.59.103"
port = 8125

[http]
address = "192.168.1.99"
max_connections = 20
port = 8080
buffer_size = 16384
answer_404 = "./404.html"
answer_503 = "./503.html"

[applications]

[applications.webapp]
hostname = "sozu.local"
frontends = [ "HTTP" ] # list of proxy tags
backends  = [ "192.168.1.21:8080", "192.168.1.22:8080", "192.168.1.23:8080"] # list of IP/port 






