# sozu proxy simple demo config file

command_socket = "/demo/command_folder/sock"
saved_state    = "/demo/state.json"
log_level      = "info"
log_target     = "stdout"
command_buffer_size = 16384
worker_count = 3
handle_process_affinity = false

# you need this, but currently it`s not used
[metrics]
address = "172.20.0.99"
port = 8125

[http]
address = "172.20.0.99"
max_connections = 20
port = 8080
buffer_size = 16384
answer_404 = "/demo/404.html"
answer_503 = "/demo/503.html"

[applications]

[applications.webapp]
hostname = "sozu.local"
frontends = [ "HTTP" ] # list of proxy tags
backends  = [ "172.20.0.11:8080", "172.20.0.12:8080", "172.20.0.13:8080"] # list of IP/port 






